import {
  Phone,
  Zap,
  MessageSquare,
  Settings,
  Headphones,
  RotateCw,
  Radio,
  Eye,
  Bot,
  Cpu,
  TrendingUp,
  MessageCircle,
  Square,
  Globe,
  Users,
  CreditCard,
  Code,
} from 'lucide-react';

export const megaMenuConfig = {
  tabs: [
    {
      id: 'voice',
      label: 'Voice & Calling',
      items: [
        {
          id: 'did-numbers',
          label: 'DID Numbers',
          description: 'Dedicated numbers for business calls',
          icon: Phone,
          path: '/products/did-numbers',
        },
        {
          id: 'sip-trunks',
          label: 'SIP Trunks',
          description: 'Reliable SIP connectivity',
          icon: Zap,
          path: '/products/sip-trunks',
        },
        {
          id: 'cloud-call-center',
          label: 'Cloud Call Center',
          description: 'Scalable call center platform',
          icon: Headphones,
          path: '/products/cloud-call-center',
        },
        {
          id: 'dialer',
          label: 'Auto / Manual Dialer',
          description: 'Outbound calling automation',
          icon: RotateCw,
          path: '/products/dialer',
        },
        {
          id: 'ivr-routing',
          label: 'IVR & Call Routing',
          description: 'Intelligent call distribution',
          icon: Radio,
          path: '/products/ivr-routing',
        },
        {
          id: 'call-monitoring',
          label: 'Call Recording & Monitoring',
          description: 'Recording & analytics',
          icon: Eye,
          path: '/products/call-monitoring',
        },
      ],
    },
    {
      id: 'ai',
      label: 'AI & Automation',
      items: [
        {
          id: 'ai-receptionist',
          label: 'AI Receptionist',
          description: 'Intelligent inbound call handling',
          icon: Bot,
          path: '/products/ai-receptionist',
        },
        {
          id: 'ai-voice-agents',
          label: 'AI Voice Agents',
          description: 'Programmable conversational AI',
          icon: Cpu,
          path: '/products/ai-voice-agents',
        },
        {
          id: 'ai-outbound',
          label: 'AI Outbound Calling',
          description: 'Intelligent outbound campaigns',
          icon: TrendingUp,
          path: '/products/ai-outbound',
          badge: 'Phase-2',
        },
        {
          id: 'conversational-ivr',
          label: 'Conversational IVR',
          description: 'Natural language call flows',
          icon: MessageCircle,
          path: '/products/conversational-ivr',
        },
      ],
    },
    {
      id: 'channels',
      label: 'Channels',
      items: [
        {
          id: 'whatsapp-automation',
          label: 'WhatsApp Automation',
          description: 'WhatsApp Business integration',
          icon: MessageSquare,
          path: '/products/whatsapp-automation',
        },
        {
          id: 'click-to-call',
          label: 'Click-to-Call Widgets',
          description: 'Embed call buttons on websites',
          icon: Square,
          path: '/products/click-to-call',
        },
      ],
    },
    {
      id: 'platform',
      label: 'Platform',
      items: [
        {
          id: 'white-label',
          label: 'White-Label Platform',
          description: 'Build your own telecom brand',
          icon: Globe,
          path: '/platform/white-label',
        },
        {
          id: 'reseller',
          label: 'Reseller Enablement',
          description: 'Become a telecom partner',
          icon: Users,
          path: '/platform/reseller',
        },
        {
          id: 'billing',
          label: 'Prepaid Billing & Wallet',
          description: 'Usage-based billing system',
          icon: CreditCard,
          path: '/platform/billing',
        },
        {
          id: 'controls',
          label: 'Monitoring & Controls',
          description: 'Real-time dashboards & alerts',
          icon: Settings,
          path: '/platform/controls',
        },
        {
          id: 'api',
          label: 'APIs & Webhooks',
          description: 'Integration & automation',
          icon: Code,
          path: '/developers/api',
        },
      ],
    },
  ],
};

export default megaMenuConfig;
